spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: VelaWear
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    locations: classpath:db/migration
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      repositories:
        enabled: false
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

server:
  port: ${SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

jwt:
  access-token-secret-key: ${JWT_ACCESS_TOKEN_SECRET_KEY}
  refresh-token-secret-key: ${JWT_REFRESH_TOKEN_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

app:
  upload:
    base-dir: ./uploads
    url-prefix: /uploads
    max-size-bytes: 5242880
    allowed-extensions:
      - jpg
      - jpeg
      - png
      - webp
    allowed-folders:
      - avatars
      - logos

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
    persist-authorization: true
