-- Sale Campaign expand migration. V15 removes the legacy product_variants.sale_price
-- after the application has switched to campaign-backed pricing.

CREATE TABLE sale_campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    banner_url VARCHAR(500),
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_by BIGINT,
    published_by BIGINT,
    published_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_sale_campaigns PRIMARY KEY (id),
    CONSTRAINT uq_sale_campaigns_code UNIQUE (code),
    CONSTRAINT fk_sale_campaigns_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_sale_campaigns_published_by FOREIGN KEY (published_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT ck_sale_campaigns_type CHECK (type IN ('STANDARD', 'FLASH')),
    CONSTRAINT ck_sale_campaigns_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'CANCELLED')),
    CONSTRAINT ck_sale_campaigns_time CHECK (ends_at > starts_at)
);

CREATE TABLE sale_campaign_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    campaign_id BIGINT NOT NULL,
    variant_id BIGINT NOT NULL,
    reference_price NUMERIC(15,2) NOT NULL,
    promotional_price NUMERIC(15,2) NOT NULL,
    quota INTEGER,
    reserved_quantity INTEGER NOT NULL DEFAULT 0,
    sold_quantity INTEGER NOT NULL DEFAULT 0,
    max_per_customer INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_sale_campaign_items PRIMARY KEY (id),
    CONSTRAINT uq_sale_campaign_items_campaign_variant UNIQUE (campaign_id, variant_id),
    CONSTRAINT fk_sale_campaign_items_campaign FOREIGN KEY (campaign_id) REFERENCES sale_campaigns(id) ON DELETE CASCADE,
    CONSTRAINT fk_sale_campaign_items_variant FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE RESTRICT,
    CONSTRAINT ck_sale_campaign_items_prices CHECK (
        reference_price >= 0 AND promotional_price > 0 AND promotional_price < reference_price
    ),
    CONSTRAINT ck_sale_campaign_items_quota CHECK (quota IS NULL OR quota > 0),
    CONSTRAINT ck_sale_campaign_items_reserved CHECK (reserved_quantity >= 0),
    CONSTRAINT ck_sale_campaign_items_sold CHECK (sold_quantity >= 0),
    CONSTRAINT ck_sale_campaign_items_capacity CHECK (
        quota IS NULL OR reserved_quantity + sold_quantity <= quota
    ),
    CONSTRAINT ck_sale_campaign_items_customer_limit CHECK (
        max_per_customer IS NULL OR (max_per_customer > 0 AND (quota IS NULL OR max_per_customer <= quota))
    )
);

CREATE TABLE sale_customer_usages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    campaign_item_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reserved_quantity INTEGER NOT NULL DEFAULT 0,
    purchased_quantity INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_sale_customer_usages PRIMARY KEY (id),
    CONSTRAINT uq_sale_customer_usages_item_user UNIQUE (campaign_item_id, user_id),
    CONSTRAINT fk_sale_customer_usages_item FOREIGN KEY (campaign_item_id) REFERENCES sale_campaign_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_sale_customer_usages_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT ck_sale_customer_usages_reserved CHECK (reserved_quantity >= 0),
    CONSTRAINT ck_sale_customer_usages_purchased CHECK (purchased_quantity >= 0)
);

ALTER TABLE orders
    ADD COLUMN payment_due_at TIMESTAMPTZ,
    ADD COLUMN reservation_expires_at TIMESTAMPTZ,
    ADD COLUMN resources_released_at TIMESTAMPTZ,
    ADD COLUMN checkout_idempotency_key VARCHAR(100),
    ADD COLUMN checkout_request_hash VARCHAR(64);

ALTER TABLE order_items
    ADD COLUMN list_price NUMERIC(15,2),
    ADD COLUMN price_source VARCHAR(30) NOT NULL DEFAULT 'BASE',
    ADD COLUMN sale_campaign_item_id BIGINT,
    ADD COLUMN sale_campaign_code VARCHAR(50),
    ADD COLUMN sale_campaign_name VARCHAR(255);

UPDATE order_items SET list_price = price WHERE list_price IS NULL;
ALTER TABLE order_items ALTER COLUMN list_price SET NOT NULL;

ALTER TABLE order_items
    ADD CONSTRAINT fk_order_items_sale_campaign_item
        FOREIGN KEY (sale_campaign_item_id) REFERENCES sale_campaign_items(id) ON DELETE RESTRICT,
    ADD CONSTRAINT ck_order_items_list_price CHECK (list_price >= 0),
    ADD CONSTRAINT ck_order_items_price_source CHECK (price_source IN ('BASE', 'STANDARD_SALE', 'FLASH_SALE')),
    ADD CONSTRAINT ck_order_items_sale_source CHECK (
        (price_source = 'BASE' AND sale_campaign_item_id IS NULL)
        OR (price_source IN ('STANDARD_SALE', 'FLASH_SALE') AND sale_campaign_item_id IS NOT NULL)
    );

CREATE TABLE sale_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    campaign_item_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    reserved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMPTZ,
    released_at TIMESTAMPTZ,
    reversed_at TIMESTAMPTZ,
    CONSTRAINT pk_sale_allocations PRIMARY KEY (id),
    CONSTRAINT uq_sale_allocations_order_item UNIQUE (order_item_id),
    CONSTRAINT fk_sale_allocations_item FOREIGN KEY (campaign_item_id) REFERENCES sale_campaign_items(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sale_allocations_order_item FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sale_allocations_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT ck_sale_allocations_quantity CHECK (quantity > 0),
    CONSTRAINT ck_sale_allocations_status CHECK (status IN ('RESERVED', 'CONFIRMED', 'RELEASED', 'REVERSED'))
);

ALTER TABLE orders DROP CONSTRAINT ck_orders_payment_method;
ALTER TABLE orders ADD CONSTRAINT ck_orders_payment_method
    CHECK (payment_method IN ('COD', 'VNPAY', 'MOMO', 'BANK_TRANSFER', 'SEPAY'));

ALTER TABLE orders DROP CONSTRAINT ck_orders_payment_status;
ALTER TABLE orders ADD CONSTRAINT ck_orders_payment_status
    CHECK (payment_status IN ('UNPAID', 'PAID', 'FAILED', 'REFUNDED', 'REFUND_PENDING'));

ALTER TABLE payments DROP CONSTRAINT ck_payments_provider;
ALTER TABLE payments ADD CONSTRAINT ck_payments_provider
    CHECK (provider IN ('COD', 'VNPAY', 'MOMO', 'STRIPE', 'SEPAY'));

ALTER TABLE payments DROP CONSTRAINT ck_payments_status;
ALTER TABLE payments ADD CONSTRAINT ck_payments_status
    CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUNDED', 'REFUND_PENDING'));

ALTER TABLE payment_transactions DROP CONSTRAINT ck_payment_transactions_status;
ALTER TABLE payment_transactions ADD CONSTRAINT ck_payment_transactions_status
    CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUND_PENDING'));

ALTER TABLE orders
    ADD CONSTRAINT uq_orders_user_idempotency UNIQUE (user_id, checkout_idempotency_key),
    ADD CONSTRAINT ck_orders_idempotency_pair CHECK (
        (checkout_idempotency_key IS NULL AND checkout_request_hash IS NULL)
        OR (checkout_idempotency_key IS NOT NULL AND checkout_request_hash IS NOT NULL)
    );

CREATE INDEX idx_sale_campaigns_public_window
    ON sale_campaigns(type, status, starts_at, ends_at);
CREATE INDEX idx_sale_campaign_items_variant ON sale_campaign_items(variant_id);
CREATE INDEX idx_sale_campaign_items_campaign ON sale_campaign_items(campaign_id);
CREATE INDEX idx_sale_customer_usages_user ON sale_customer_usages(user_id);
CREATE INDEX idx_sale_allocations_item_status ON sale_allocations(campaign_item_id, status);
CREATE INDEX idx_sale_allocations_user ON sale_allocations(user_id);
CREATE INDEX idx_orders_expiring_reservations
    ON orders(reservation_expires_at)
    WHERE status = 'PENDING' AND payment_status = 'UNPAID' AND resources_released_at IS NULL;
CREATE INDEX idx_order_items_sale_campaign_item ON order_items(sale_campaign_item_id);

CREATE TRIGGER trg_sale_campaigns_set_updated_at
BEFORE UPDATE ON sale_campaigns
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_sale_campaign_items_set_updated_at
BEFORE UPDATE ON sale_campaign_items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_sale_customer_usages_set_updated_at
BEFORE UPDATE ON sale_customer_usages
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO permissions (name, api_path, method, module)
VALUES
    ('VIEW_SALE_CAMPAIGNS', '/api/v1/sale-campaigns', 'GET', 'SALE'),
    ('VIEW_SALE_CAMPAIGN', '/api/v1/sale-campaigns/{id}', 'GET', 'SALE'),
    ('CREATE_SALE_CAMPAIGN', '/api/v1/sale-campaigns', 'POST', 'SALE'),
    ('UPDATE_SALE_CAMPAIGN', '/api/v1/sale-campaigns/{id}', 'PUT', 'SALE'),
    ('DELETE_SALE_CAMPAIGN', '/api/v1/sale-campaigns/{id}', 'DELETE', 'SALE'),
    ('PUBLISH_SALE_CAMPAIGN', '/api/v1/sale-campaigns/{id}/publish', 'POST', 'SALE'),
    ('CANCEL_SALE_CAMPAIGN', '/api/v1/sale-campaigns/{id}/cancel', 'POST', 'SALE'),
    ('UPDATE_LIVE_SALE_DISPLAY', '/api/v1/sale-campaigns/{id}/display', 'PATCH', 'SALE'),
    ('INCREASE_FLASH_QUOTA', '/api/v1/sale-campaigns/{id}/items/{itemId}/increase-quota', 'POST', 'SALE'),
    ('END_SALE_CAMPAIGN', '/api/v1/sale-campaigns/{id}/end', 'POST', 'SALE'),
    ('END_AND_CLONE_SALE_CAMPAIGN', '/api/v1/sale-campaigns/{id}/end-and-clone', 'POST', 'SALE'),
    ('PREVIEW_CHECKOUT', '/api/v1/checkout/preview', 'POST', 'CHECKOUT'),
    ('CANCEL_MY_ORDER', '/api/v1/checkout/{orderId}/cancel', 'POST', 'CHECKOUT')
ON CONFLICT (api_path, method) DO UPDATE
SET name = EXCLUDED.name, module = EXCLUDED.module;

INSERT INTO permission_role (permission_id, role_id)
SELECT p.id, r.id FROM permissions p CROSS JOIN roles r
WHERE p.module = 'SALE' AND r.name IN ('ADMIN', 'MANAGER')
ON CONFLICT DO NOTHING;

INSERT INTO permission_role (permission_id, role_id)
SELECT p.id, r.id FROM permissions p CROSS JOIN roles r
WHERE p.name IN ('VIEW_SALE_CAMPAIGNS', 'VIEW_SALE_CAMPAIGN') AND r.name = 'STAFF'
ON CONFLICT DO NOTHING;

INSERT INTO permission_role (permission_id, role_id)
SELECT p.id, r.id FROM permissions p CROSS JOIN roles r
WHERE p.name IN ('PREVIEW_CHECKOUT', 'CANCEL_MY_ORDER')
  AND r.name IN ('ADMIN', 'MANAGER', 'STAFF', 'USER')
ON CONFLICT DO NOTHING;
