CREATE TABLE email_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_type VARCHAR(50) NOT NULL,
    order_id BIGINT NOT NULL,
    recipient_email VARCHAR(255) NOT NULL,
    template_key VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    claim_token UUID,
    lease_expires_at TIMESTAMPTZ,
    provider_message_id VARCHAR(255),
    last_error TEXT,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_email_outbox PRIMARY KEY (id),
    CONSTRAINT uq_email_outbox_event_order UNIQUE (event_type, order_id),
    CONSTRAINT fk_email_outbox_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
    CONSTRAINT ck_email_outbox_event_type CHECK (event_type IN ('ORDER_COMPLETED')),
    CONSTRAINT ck_email_outbox_template_key CHECK (template_key IN ('ORDER_COMPLETED')),
    CONSTRAINT ck_email_outbox_status CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'FAILED')),
    CONSTRAINT ck_email_outbox_attempt_count CHECK (attempt_count >= 0),
    CONSTRAINT ck_email_outbox_claim CHECK (
        (status = 'PROCESSING' AND claim_token IS NOT NULL AND lease_expires_at IS NOT NULL)
        OR (status <> 'PROCESSING' AND claim_token IS NULL AND lease_expires_at IS NULL)
    ),
    CONSTRAINT ck_email_outbox_sent CHECK (
        (status = 'SENT' AND sent_at IS NOT NULL)
        OR (status <> 'SENT' AND sent_at IS NULL)
    )
);

CREATE INDEX idx_email_outbox_pending
    ON email_outbox(next_attempt_at, id)
    WHERE status = 'PENDING';

CREATE INDEX idx_email_outbox_expired_lease
    ON email_outbox(lease_expires_at, id)
    WHERE status = 'PROCESSING';

CREATE TRIGGER trg_email_outbox_set_updated_at
BEFORE UPDATE ON email_outbox
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
