CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    type VARCHAR(50) NOT NULL,
    target_type VARCHAR(50),
    target_id VARCHAR(100),
    link_url VARCHAR(255),
    image_url VARCHAR(500),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_notifications PRIMARY KEY (id),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT ck_notifications_type CHECK (type IN ('ORDER_UPDATE', 'PROMOTION', 'SYSTEM', 'PAYMENT')),
    CONSTRAINT ck_notifications_target_type CHECK (target_type IS NULL OR target_type IN ('ORDER', 'PRODUCT', 'SALE_CAMPAIGN', 'COUPON'))
);

CREATE INDEX idx_notifications_user_created ON notifications (user_id, created_at DESC);

CREATE INDEX idx_notifications_user_unread ON notifications (user_id) WHERE is_read = FALSE;

-- Seed RBAC permissions
INSERT INTO permissions (name, api_path, method, module)
VALUES
    ('VIEW_MY_NOTIFICATIONS',      '/api/v1/notifications/me',              'GET', 'NOTIFICATION'),
    ('VIEW_MY_UNREAD_NOTIF_COUNT', '/api/v1/notifications/me/unread-count', 'GET', 'NOTIFICATION'),
    ('READ_NOTIFICATION',          '/api/v1/notifications/{id}/read',       'PUT', 'NOTIFICATION'),
    ('READ_ALL_MY_NOTIFICATIONS',  '/api/v1/notifications/me/read-all',      'PUT', 'NOTIFICATION')
ON CONFLICT (api_path, method) DO UPDATE
SET
    name   = EXCLUDED.name,
    module = EXCLUDED.module;

-- Grant permissions to roles
INSERT INTO permission_role (permission_id, role_id)
SELECT p.id, r.id
FROM permissions p
CROSS JOIN roles r
WHERE p.module = 'NOTIFICATION'
ON CONFLICT DO NOTHING;
